In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np

2022-05-12 00:03:32.370914: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-05-12 00:03:32.370974: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "


In [55]:
inputfile = "./RELIANCE.NS.csv"
data = pd.read_csv(inputfile)
data = data.drop(['Date','Adj Close','Volume'],axis=1)
npdata = np.array(data)
Y = npdata[2:] #Y
npdataUp = npdata[1:-1]
npdata = npdata[:-2]
X = np.hstack([npdata,npdataUp]) #X
# X = pd.DataFrame(X)
# Y = pd.DataFrame(Y)

In [56]:
train_X = X[:-380]
test_X = X[-380:]
train_Y = Y[:-380]
test_Y = Y[-380:]

In [58]:
print(test_X)
print(test_Y)

[[1084.718018 1096.902466 1036.376221 ... 1064.707642 1010.42218
  1020.774109]
 [1030.828735 1064.707642 1010.42218  ... 1119.191162 1038.159302
  1103.29187 ]
 [1063.865601 1119.191162 1038.159302 ... 1114.040039 1035.38562
  1070.304565]
 ...
 [2553.       2574.850098 2537.050049 ... 2612.       2547.350098
  2609.199951]
 [2555.100098 2612.       2547.350098 ... 2619.949951 2551.100098
  2559.850098]
 [2619.949951 2619.949951 2551.100098 ... 2598.75     2567.699951
  2572.399902]]
[[1063.865601 1119.191162 1038.159302 1103.29187 ]
 [1111.712036 1114.040039 1035.38562  1070.304565]
 [1123.797485 1123.797485 1046.381348 1067.332764]
 ...
 [2619.949951 2619.949951 2551.100098 2559.850098]
 [2595.       2598.75     2567.699951 2572.399902]
 [2585.25     2684.399902 2581.5      2671.25    ]]


In [59]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=8, activation='sigmoid',input_shape=(8,)),
    tf.keras.layers.Dense(units=2, activation='sigmoid'),
    tf.keras.layers.Dense(units=2, activation='sigmoid'),
    tf.keras.layers.Dense(units=4, activation='sigmoid'),
])
# model.summary()

In [67]:
model.compile(optimizer=tf.optimizers.SGD(),loss=tf.keras.losses.MeanAbsoluteError(),metrics=['accuracy'])
model.fit(train_X,train_Y,epochs=10, batch_size=25)

Epoch 1/10
113/113 [==============================] - 1s 2ms/step - loss: 620.2695 - accuracy: 0.9361
Epoch 2/10
113/113 [==============================] - 0s 2ms/step - loss: 620.2653 - accuracy: 0.9361
Epoch 3/10
113/113 [==============================] - 0s 3ms/step - loss: 620.2615 - accuracy: 0.9361
Epoch 4/10
113/113 [==============================] - 0s 3ms/step - loss: 620.2577 - accuracy: 0.9361
Epoch 5/10
113/113 [==============================] - 0s 3ms/step - loss: 620.2546 - accuracy: 0.9361
Epoch 6/10
113/113 [==============================] - 0s 3ms/step - loss: 620.2516 - accuracy: 0.9361
Epoch 7/10
113/113 [==============================] - 0s 3ms/step - loss: 620.2488 - accuracy: 0.9361
Epoch 8/10
113/113 [==============================] - 0s 3ms/step - loss: 620.2463 - accuracy: 0.9361
Epoch 9/10
113/113 [==============================] - 0s 4ms/step - loss: 620.2439 - accuracy: 0.9361
Epoch 10/10
113/113 [==============================] - 0s 4ms/step - loss: 620.241

In [61]:
model.evaluate(test_X,test_Y)

12/12 [==============================] - 0s 1ms/step - loss: 1992.6661 - accuracy: 0.9263


[1992.6661376953125, 0.9263157844543457]

In [66]:
q = np.array([[1,2,3,4,5,6,7,8]])
print(q)
prediction = model.predict(q)
print(prediction)
q = np.array([test_X[1]])
print(q)
prediction = model.predict(q)
print(prediction)
q = np.array([test_X[2]])
print(q)
prediction = model.predict(q)
print(prediction)

[[1 2 3 4 5 6 7 8]]
[[0.90650433 0.93951917 0.8819434  0.9098856 ]]
[[1030.828735 1064.707642 1010.42218  1020.774109 1063.865601 1119.191162
  1038.159302 1103.29187 ]]
[[0.9066736  0.9396191  0.8819046  0.91004866]]
[[1063.865601 1119.191162 1038.159302 1103.29187  1111.712036 1114.040039
  1035.38562  1070.304565]]
[[0.9066736  0.9396191  0.8819046  0.91004866]]
